### ISSUE TITLE
How do you save splits?

### ISSUE THREAD

**Issue by TurtleTony** [CryZe/livesplit-one-desktop#13]
I've noticed that there seem to be no buttons to save pb's etc. and when restarting the program everything is back to 0. Is there any way so save splits for now or do I just have to manually put them into the .lss file?

**Comment by CryZe** [comment]
At the moment you have to bring the window in focus and then press the enter key to save the splits. It's not great, but this is how it is until we have a proper user interface.

Tell me if that works for you.

**Comment by TurtleTony** [comment]
That's great to know, thank you. I can confirm the splits are saved properly. (I'm on linux manjaro)
