### ISSUE TITLE
Feature Request:  Basic Documentation Markdown or Wiki?

### ISSUE THREAD

**Issue by 3vi1** [CryZe/livesplit-one-desktop#15]
I compiled this on Linux last night and found it very easy to build and run.  However, judging from tutorials I found, the interface doesn't seem to work like the "classic" Livesplit (i.e. right-clicking the interface does nothing) nor are there configuration buttons to add splits like on the Livesplit One web site.

After pressing every key on the keyboard, I've been able to determine are that 1,3,5,8, and 9 on the numeric keypad have various effects, I've never used any version of Livesplit before - and without being able to get to a settings/hotkeys menu it's not intuitive how to do anything beyond a marathon timer.

Is there documentation that I've just missed?  Or has this project not gotten to that point because an interface to set up splits and/or change hotkeys is not yet implemented?

Thanks.

[https://i.imgur.com/oZoUaws.png](https://i.imgur.com/oZoUaws.png)

**Comment by wooferzfg** [comment]
> Or has this project not gotten to that point because an interface to set up splits and/or change hotkeys is not yet implemented?

Yeah, that's pretty much the case. We're hoping to clean this project up a bit and move it over to the LiveSplit organization soon.

**Comment by 3vi1** [comment]
That's cool; I'll check back in the future to see how it's progressed.  Thanks for the info!

**Comment by CryZe** [comment]
Closing this for now as we don't plan to write any additional documentation for this prototype version. The version with a proper GUI is going to be up at some point in the future.
