### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by jumper-cable-morty** [CryZe/livesplit-one-desktop#21]
Running on Endeavor OS, based off of Arch Linux. (Not sure if that's super relevant but I wanna add as much info as I can about this.) Everything compiled fine after running `cargo run` but whenever it tries to launch, it just does a small blip for the window, opening then closing immediately. It gives me this in the terminal: `thread 'main' panicked at 'called` \`Result::unwrap()\` `on an `Err` value: Timeout', src/renderer/mod.rs:448:57
note: run with` \`RUST_BACKTRACE=1\` `environment variable to display a backtrace
Aborted (core dumped)`

**Comment by CryZe** [comment]
This is likely resolved now. Can you check again?

**Comment by jumper-cable-morty** [comment]
I can't actually boot that installation anymore so I can't check it. Should I go ahead and close the issue?

**Comment by CryZe** [comment]
Yeah feel free to open a new one whenever then.
